

sudo apt update
sudo apt upgrade



sudo apt install wayland


sudo apt install weston


weston

sudo apt install snapd


sway

sudo nano /etc/apt/sources.list

# deb http://security.ubuntu.com/ubuntu noble-security InRelease
# deb http://archive.ubuntu.com/ubuntu noble InRelease
# deb http://archive.ubuntu.com/ubuntu noble-updates InRelease
# deb http://packages.linuxmint.com wilma InRelease

ulozit ctrl+o entr zavřít ctrl+x

sudo nano /etc/apt/sources.list.d/official-package-repositories.list

# deb http://archive.ubuntu.com/ubuntu/ jammy main restricted universe multiver>
# deb http://archive.ubuntu.com/ubuntu/ jammy-updates main restricted universe >
# deb http://archive.ubuntu.com/ubuntu/ jammy-backports main restricted univers>
# deb http://security.ubuntu.com/ubuntu jammy-security main restricted universe>
# Do not edit this file manually, use Software Sources instead.

# deb http://packages.linuxmint.com wilma main upstream import backport #id:lin>

# deb http://archive.ubuntu.com/ubuntu noble main restricted universe multiverse
# deb http://archive.ubuntu.com/ubuntu noble-updates main restricted universe m>
# deb http://archive.ubuntu.com/ubuntu noble-backports main restricted universe>

# deb http://security.ubuntu.com/ubuntu/ noble-security main restricted univers>



widget   conky &



nano ~/.conkyrc

conky.config = {
    alignment = 'top_right',
    gap_x = 10,
    gap_y = 10,
    update_interval = 300,  -- aktualizace každých 5 minut
    double_buffer = true,
    background = false,
    own_window = true,
    own_window_type = 'desktop', -- zkus také 'normal'
    own_window_transparent = true,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    use_xft = true,
    font = 'DejaVu Sans Mono:size=10',
    xftalpha = 0.8,
    override_utf8_locale = true,
    uppercase = false,
    default_color = 'white',
};

conky.text = [[
${color yellow}${time %a, %b %d %H:%M:%S}
CPU: ${cpu cpu0}% ${cpubar cpu0}
RAM: $mem/$memmax - $memperc% ${membar 4}
Disk: $diskio_read/$diskio_write

${color yellow}BTC Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=USD" | jq -r '.USD'} USD
]];


nano ~/.conkyrc


killall conky
conky &

jq --version

sudo apt install jq   


conky.config = {
    alignment = 'top_right',
    gap_x = 10,
    gap_y = 10,
    update_interval = 300,
    double_buffer = true,
    own_window = true,
    own_window_type = 'desktop',  -- Změněno na 'desktop'
    own_window_transparent = true,
    use_xft = true,
    font = 'DejaVu Sans Mono:size=10',
    xftalpha = 0.8,
    override_utf8_locale = true,
    uppercase = false,
    default_color = 'green',
};

conky.text = [[
${color green}Network: ${color green}${wireless essid wlan0} ${addr wlan0} ${downspeed wlan0} ↓ ${upspeed wlan0} ↑
${color green}CPU Temp: ${color green}${execi 10 sensors | grep 'Core 0' | awk '{print $3}'}
${color green}Battery: ${color green}${battery_percent BAT0}% ${battery_time BAT0}
${color green}Updates: ${color green}${execi 3600 apt-get -s upgrade | grep -P '^\d' | wc -l} available
${color green}Disk Usage: ${color green}${fs_used /}/${fs_size /} (${fs_used_perc /}%)
${color green}Top Processes: ${color green}${top name 1} (${top cpu 1}%)
${color green}Next Event: ${color green}${execi 300 gcalcli next --noheader | awk '{print $1, $2, $3}'}
${color green}Last 5 Log Entries: ${color green}${execi 300 tail -n 5 /var/log/syslog}

${color green}${time %a, %b %d %H:%M:%S}
CPU: ${color green}${cpu cpu0}% ${cpubar cpu0}
RAM: ${color green}$mem/$memmax - $memperc% ${membar 4}
Disk: ${color green}$diskio_read/$diskio_write

${color green}BTC Price: ${color green}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=BTC&tsy








conky.config = {
    alignment = 'top_right',
    gap_x = 10,
    gap_y = 10,
    update_interval = 300,
    double_buffer = true,
    own_window = true,
    own_window_type = 'desktop',  -- Změněno na 'desktop'
    own_window_transparent = true,
    use_xft = true,
    font = 'DejaVu Sans Mono:size=10',
    xftalpha = 0.8,
    override_utf8_locale = true,
    uppercase = false,
    default_color = 'white',
};

conky.text = [[
${color yellow}Network: ${color white}${wireless essid wlan0} ${addr wlan0} ${downspeed wlan0} ↓ ${upspeed wlan0} ↑
${color yellow}CPU Temp: ${color white}${execi 10 sensors | grep 'Core 0' | awk '{print $3}'}
${color yellow}Battery: ${color white}${battery_percent BAT0}% ${battery_time BAT0}
${color yellow}Updates: ${color white}${execi 3600 apt-get -s upgrade | grep -P '^\d' | wc -l} available
${color yellow}Disk Usage: ${color white}${fs_used /}/${fs_size /} (${fs_used_perc /}%)
${color yellow}Top Processes: ${color white}${top name 1} (${top cpu 1}%)
${color yellow}Next Event: ${color white}${execi 300 gcalcli next --noheader | awk '{print $1, $2, $3}'}
${color yellow}Last 5 Log Entries: ${color white}${execi 300 tail -n 5 /var/log/syslog}

${color yellow}${time %a, %b %d %H:%M:%S}
CPU: ${cpu cpu0}% ${cpubar cpu0}
RAM: $mem/$memmax - $memperc% ${membar 4}
Disk: $diskio_read/$diskio_write

${color yellow}BTC Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=USD" | jq -r '.USD'} USD
${color yellow}ETH Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=USD" | jq -r '.USD'} USD
${color yellow}ATOM Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=ATOM&tsyms=USD" | jq -r '.USD'} USD
${color yellow}PEPE Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=PEPE&tsyms=USD" | jq -r '.USD'} USD
${color yellow}XRP Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=XRP&tsyms=USD" | jq -r '.USD'} USD
${color yellow}FORH Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=FORH&tsyms=USD" | jq -r '.USD'} USD
${color yellow}BTSG Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=BTSG&tsyms=USD" | jq -r '.USD'} USD
${color yellow}APT Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=APT&tsyms=USD" | jq -r '.USD'} USD
${color yellow}STRD Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=STRD&tsyms=USD" | jq -r '.USD'} USD
${color yellow}TOTAL1 Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=TOTAL1&tsyms=USD" | jq -r '.USD'} USD
${color yellow}TOTAL2 Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=TOTAL2&tsyms=USD" | jq -r '.USD'} USD
${color yellow}TOTAL3 Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=TOTAL3&tsyms=USD" | jq -r '.USD'} USD
]];



conky.config = {
    alignment = 'top_right',
    gap_x = 10,
    gap_y = 10,
    update_interval = 300,
    double_buffer = true,
    own_window = true,
    own_window_type = 'desktop',  -- Změněno na 'desktop'
    own_window_transparent = true,
    use_xft = true,
    font = 'DejaVu Sans Mono:size=10',
    xftalpha = 0.8,
    override_utf8_locale = true,
    uppercase = false,
    default_color = 'white',
};

conky.text = [[
${color yellow}${time %a, %b %d %H:%M:%S}
CPU: ${cpu cpu0}% ${cpubar cpu0}
RAM: $mem/$memmax - $memperc% ${membar 4}
Disk: $diskio_read/$diskio_write

${color yellow}BTC Price: ${color white}${execi 300 curl -s "https://min-api.cr>
${color yellow}ETH Price: ${color white}${execi 300 curl -s "https://min-api.cr>
${color yellow}ATOM Price: ${color white}${execi 300 curl -s "https://min-api.c>
${color yellow}PEPE Price: ${color white}${execi 300 curl -s "https://min-api.c>
${color yellow}XRP Price: ${color white}${execi 300 curl -s "https://min-api.cr>
]];








conky.text = [[
${color yellow}${time %a, %b %d %H:%M:%S}
CPU: ${cpu cpu0}% ${cpubar cpu0}
RAM: $mem/$memmax - $memperc% ${membar 4}
Disk: $diskio_read/$diskio_write

${color yellow}BTC Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=USD" | jq -r '.USD'} USD
${color yellow}ETH Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=USD" | jq -r '.USD'} USD
${color yellow}ATOM Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=ATOM&tsyms=USD" | jq -r '.USD'} USD
${color yellow}PEPE Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=PEPE&tsyms=USD" | jq -r '.USD'} USD
${color yellow}XRP Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=XRP&tsyms=USD" | jq -r '.USD'} USD
]];




conky.config = {
    alignment = 'top_right',
    gap_x = 10,
    gap_y = 10,
    update_interval = 300,
    double_buffer = true,
    own_window = true,
    own_window_type = 'normal',
    own_window_transparent = true,
    use_xft = true,
    font = 'DejaVu Sans Mono:size=10',
    xftalpha = 0.8,
    override_utf8_locale = true,
    uppercase = false,
    default_color = 'white',
};

conky.text = [[
${color yellow}${time %a, %b %d %H:%M:%S}
CPU: ${cpu cpu0}% ${cpubar cpu0}
RAM: $mem/$memmax - $memperc% ${membar 4}
Disk: $diskio_read/$diskio_write

${color yellow}BTC Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=USD" | jq -r '.USD'} USD
${color yellow}ETH Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=USD" | jq -r '.USD'} USD
${color yellow}ATOM Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=ATOM&tsyms=USD" | jq -r '.USD'} USD
${color yellow}PEPE Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=PEPE&tsyms=USD" | jq -r '.USD'} USD
${color yellow}XRP Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=XRP&tsyms=USD" | jq -r '.USD'} USD
]];
    





conky.config = {
    alignment = 'top_right',
    gap_x = 10,
    gap_y = 10,
    update_interval = 300,
    double_buffer = true,
    own_window = true,
    own_window_type = 'desktop',  -- Změněno na 'desktop'
    own_window_transparent = true,
    use_xft = true,
    font = 'DejaVu Sans Mono:size=10',
    xftalpha = 0.8,
    override_utf8_locale = true,
    uppercase = false,
    default_color = 'white',
};

conky.text = [[
${color yellow}Network: ${color white}${wireless essid wlan0} ${addr wlan0} ${downspeed wlan0} ↓ ${upspeed wlan0} ↑
${color yellow}CPU Temp: ${color white}${execi 10 sensors | grep 'Core 0' | awk '{print $3}'}
${color yellow}Battery: ${color white}${battery_percent BAT0}% ${battery_time BAT0}
${color yellow}Updates: ${color white}${execi 3600 apt-get -s upgrade | grep -P '^\d' | wc -l} available
${color yellow}Disk Usage: ${color white}${fs_used /}/${fs_size /} (${fs_used_perc /}%)
${color yellow}Top Processes: ${color white}${top name 1} (${top cpu 1}%)
${color yellow}Next Event: ${color white}${execi 300 gcalcli next --noheader | awk '{print $1, $2, $3}'}
${color yellow}Last 5 Log Entries: ${color white}${execi 300 tail -n 5 /var/log/syslog}

${color yellow}${time %a, %b %d %H:%M:%S}
CPU: ${cpu cpu0}% ${cpubar cpu0}
RAM: $mem/$memmax - $memperc% ${membar 4}
Disk: $diskio_read/$diskio_write

${color yellow}BTC Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=USD" | jq -r '.USD'} USD
${color yellow}ETH Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=USD" | jq -r '.USD'} USD
${color yellow}ATOM Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=ATOM&tsyms=USD" | jq -r '.USD'} USD
${color yellow}PEPE Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=PEPE&tsyms=USD" | jq -r '.USD'} USD
${color yellow}XRP Price: ${color white}${execi 300 curl -s "https://min-api.cryptocompare.com/data/price?fsym=XRP&tsyms=USD" | jq -r '.USD'} USD
]];












$ dmesg | grep -i error
 tpm




         XMR


48ssxYzSsw4j3QzVHyn47GDY9gZkVray2QEMT8NYtzQUXjw939wc2eqYcDeJc9NUsn3yE9jwaReJo3bHUBbCXh3k6S1Kwhb



git clone https://github.com/xmrig/xmrig.git
cd xmrig
mkdir build
cd build
cmake ..
make



./xmrig -o pool.supportxmr.com:3333 -u 48ssxYzSsw4j3QzVHyn47GDY9gZkVray2QEMT8NYtzQUXjw939wc2eqYcDeJc9NUsn3yE9jwaReJo3bHUBbCXh3k6S1Kwhb
-p x --donate-level 1






btc

cat ~/.ssh/id_ed25519.pub








